In [1]:
import math
help(math.acos)

Help on built-in function acos in module math:

acos(x, /)
    Return the arc cosine (measured in radians) of x.
    
    The result is between 0 and pi.



In [2]:
math.log(5,base=2)

TypeError: log() takes no keyword arguments

### optional in notebook 2 and 3

In [1]:
def myfunction():
    """ my help """

In [2]:
help(myfunction)

Help on function myfunction in module __main__:

myfunction()
    my help



In [6]:

def multiple_return():
    return 1,2
type(multiple_return())
type(1,2)

TypeError: type() takes 1 or 3 arguments

In [20]:
(a,b)=([],[123])
print(a)
(c,d)=(a,b)
print(c)

[]
[]


In [22]:
a=[1]
c=a
a[0]=0
print(c)

a='str'
c=a
a='otherstr'
print(c)

[0]
str


In [33]:
a = ['12']*5
c= a
c[0]='21'
#a[0].extend('21')
print(c)

a = [[]]*5
c = a
c[0].append(1)
print(a)

['21', '12', '12', '12', '12']
[[1], [1], [1], [1], [1]]


In [42]:
#help(str)

In [35]:
def f(*a,b):
    print(b)
f(1,2,3,b=4)

4


In [38]:
a = [[]]*3
a[1]=[]
a[0].append(0)
print(a)

[[0], [], [0]]


In [41]:
import numpy as np
v =np.array([1,2,3])

In [ ]:
#(1,) (1)

In [45]:
type(np.arange(1,10))

numpy.ndarray

In [54]:
v= np.matrix([1,6])
np.array(v.T@v)

array([[ 1,  6],
       [ 6, 36]])

In [49]:
A= np.arange(1,6).reshape(-1,1)@ np.arange(1,6).reshape(1,-1)
v= np.arange(0,5)
print(v*A,v*A == A*v,sep = '\n')
print(A*v.reshape(-1,1))
print(v@A)
print(A@v)

[[  0   2   6  12  20]
 [  0   4  12  24  40]
 [  0   6  18  36  60]
 [  0   8  24  48  80]
 [  0  10  30  60 100]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[  0   0   0   0   0]
 [  2   4   6   8  10]
 [  6  12  18  24  30]
 [ 12  24  36  48  60]
 [ 20  40  60  80 100]]
[ 40  80 120 160 200]
[ 40  80 120 160 200]


In [58]:
#array is a row vector, and it can be column vector if needed at @
#better way to think about it, it is a 1-index thing. mat merge same dimension
#matrix is a n*m matrix, with clear shape. matrix(array) is an 1*n matrix
np.tensordot(A,A)
A;A;A+1+3

array([[ 5,  6,  7,  8,  9],
       [ 6,  8, 10, 12, 14],
       [ 7, 10, 13, 16, 19],
       [ 8, 12, 16, 20, 24],
       [ 9, 14, 19, 24, 29]])

In [ ]:
plt.subplots()

In [64]:
A = np.arange(1,5,1)
B = np.ones_like(A)
A[A != B]

array([2, 3, 4])